include: package:lints/recommended.yaml

analyzer:
  enable-experiment:
    - non-nullable
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - example/*.dart
    - test/*.dart
    